@startuml Manage Campground (DELETE)

header Campground Booking Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Campground (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:campgrounds" as routerCampgrounds
participant "<<controllers>>\n:campgrounds" as controllersCampgrounds
participant "<<model>>\n:Campground" as modelCampground
database "<<MongoDB>>\n:campgrounds" as CampgroundsDatabase

client->server ++:req.delete('/campgrounds/:id')
server->routerCampgrounds ++:app.use('/campgrounds',campgrounds)
routerCampgrounds -> controllersCampgrounds ++:deleteCampground()
controllersCampgrounds->modelCampground ++:findByIdAndDelete(req.params.id)
modelCampground ->CampgroundsDatabase ++: campgroundSchema
CampgroundsDatabase --> modelCampground --: campground
modelCampground --> controllersCampgrounds --: campground
alt Campground found
    controllersCampgrounds -> client --: 200 {success: true, data: {}}
else Campground not found
    controllersCampgrounds -> client --: 404 {success: false, message: `Campground not found with id of ${req.params.id}`}
end

@enduml